AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  Environment:
    Type: String
    Default: test
    Description: Environment name
  ServiceName:
    Type: String
    Description: |
      Name of the service in lowercase
      This should match the service value used as event source and for SSM parameters.
  EventBusName:
    Type: String
    Description: EventBridge Event Bus Name


Resources:
  Queue:
    Type: AWS::SQS::Queue

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action:
              - sqs:SendMessage
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt Rule.Arn
      Queues:
        - !Ref Queue

  Rule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      EventPattern: !Sub '{"source": [
                          { "prefix": "ecommerce.${ServiceName}" }
                          ]}'
      State: ENABLED
      Targets:
        - Id: ListenerQueue
          Arn: !GetAtt Queue.Arn

  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/ecommerce/${Environment}/${ServiceName}/listener/url"
      Type: String
      Value: !Ref Queue